# NumPy in Python
## What is NumPy?

NumPy (Numerical Python) is a Python library used for working with numerical data efficiently.

It provides a special data structure called an ndarray (N-dimensional array) which is much faster and more memory-efficient than Python lists when performing mathematical operations.

## Why Do We Use NumPy?

Suppose you have thousands or millions of numbers and want to perform calculations on them.

Using normal Python lists:

pip install numpy

In [1]:
import numpy as np
import time

# Create 10 million numbers
numbers_list = list(range(10_000_000))
numbers_array = np.array(numbers_list)

# -----------------------------
# Python List Operation
# -----------------------------
start = time.time()

result_list = [x * 2 for x in numbers_list]

end = time.time()

print(f"List Time: {end - start:.4f} seconds")

# -----------------------------
# NumPy Operation
# -----------------------------
start = time.time()

result_array = numbers_array * 2

end = time.time()

print(f"NumPy Time: {end - start:.4f} seconds")

List Time: 0.7230 seconds
NumPy Time: 0.0422 seconds


In [ ]:
import numpy as np

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [5]:
print(arr.shape)

(5,)


In [6]:
print(arr.size)

5


In [7]:
print(arr.dtype)

int64


In [8]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

10
30


In [9]:
arr = np.array([1, 2, 3])

print(arr + 10)

[11 12 13]


In [ ]:
print(arr - 1)

In [ ]:
print(arr * 2)

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [12]:
print(arr1 + arr2)

[5 7 9]


In [13]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [14]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [15]:
arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
arr = np.array([10, 20, 30, 40, 50])

In [17]:
print(np.sum(arr))

150


In [18]:
print(np.mean(arr))

30.0


In [19]:
print(np.max(arr))

50


In [20]:
print(np.min(arr))

10


In [21]:
print(np.median(arr))

30.0


In [22]:
print(np.argmax(arr))

4


In [23]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])

print(np.unique(arr))

[1 2 3 4]


In [24]:
arr = np.array([10, 20, 30])

new_arr = np.append(arr, 40)

print(new_arr)

[10 20 30 40]


In [25]:
arr = np.array([10, 20, 30, 40, 50])

indices = np.where(arr > 25)

print(indices)

(array([2, 3, 4]),)


In [26]:
arr = np.array([10, 20, 30])

lst = arr.tolist()

print(lst)
print(type(lst))

[10, 20, 30]
<class 'list'>
