In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4])

print(arr.ndim)

1


In [21]:
arr = np.array([[[1, 2] ,[3,4]],[[1, 2] ,[3,4]]])

print(arr.ndim)

3


In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ndim)

2


In [23]:
onr = np.ones((3,4))

print(onr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
onr = np.ones((3, 4), dtype=str)

print(onr)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [9]:
onr = np.ones((3, 4), dtype=int)

print(onr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
emp = np.empty((3, 4))

print(emp)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
ls = np.linspace(1, 10, 20)

print(ls)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [30]:
arr = np.arange(1, 13)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arr2d = arr.reshape(4, 3)

print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([[1,2,3],
                [4,5,6],[4,7,8]])

print(arr.ravel())

[1 2 3 4 5 6 4 7 8]


In [14]:
print(arr.flatten())

[1 2 3 4 5 6]


In [15]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [16]:
arr = np.array([[10,20,30],
                [40,50,60]])

print(arr.max())

60


In [17]:
print(arr.max(axis=0))

[40 50 60]


In [18]:
print(arr.max(axis=1))

[30 60]


In [34]:
arr1 = np.arange(1,17).reshape(4,4)

arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
arr2 = np.arange(17,33).reshape(4,4)

arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [36]:
print(np.concatenate((arr1, arr2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
